### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by asandberg17** [BMW-InnovationLab/BMW-Labeltool-Lite#14]
Attempting to run docker-compose up in the BMW-Labeltool-Lite repository results in the following error messages on Ubuntu 18.04., docker -v returns 20.10.2, and docker-compose --version returns 1.29.2

I have absolutely no idea what is going wrong or how to fix it. Any help would be greatly appreciated. 

andrew@paul-desktop:~/Desktop/pyPro/BMW_Innovations/BMW-Labeltool-Lite$ docker-compose up
Building labeltool-lite-frontend
Sending build context to Docker daemon  4.426MB
Step 1/10 : FROM node:lts as builder
 ---> 60fac455c9f4
Step 2/10 : LABEL maintainer="jon@doe.com"
 ---> Using cache
 ---> a7712da16ba3
Step 3/10 : WORKDIR /src/app
 ---> Using cache
 ---> 6b9ad6a1dcbf
Step 4/10 : COPY ./code ./
 ---> Using cache
 ---> eb58c34e89b9
Step 5/10 : RUN yarn && yarn build:prod
 ---> Running in 1f5c08eb2481
yarn install v1.22.5
info No lockfile found.
[1/4] Resolving packages...
warning @microsoft/signalr > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @microsoft/signalr > request > har-validator@5.1.5: this library is no longer supported
warning @microsoft/signalr > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @stoplight/prism-cli > @stoplight/prism-http > @stoplight/http-spec > postman-collection > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @stoplight/prism-cli > @stoplight/prism-http > @stoplight/http-spec > json-schema-generator > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning messageformat@2.3.0: Package renamed as '@messageformat/core', see messageformat.github.io for more details. 'messageformat' will eventually provide a polyfill for Intl.MessageFormat, once it's been defined by Unicode & ECMA.
warning node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @angular-builders/jest > jest-preset-angular > jest-environment-jsdom-thirteen > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @angular-builders/jest > jest-preset-angular > jest-environment-jsdom-thirteen > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @angular-builders/jest > jest-preset-angular > jest-environment-jsdom-thirteen > jest-util > @jest/fake-timers > jest-message-util > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @angular-builders/jest > jest-preset-angular > jest-environment-jsdom-thirteen > jest-util > @jest/fake-timers > jest-message-util > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @angular-devkit/build-angular > core-js@3.1.4: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning @angular-devkit/build-angular > less > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @angular-devkit/build-angular > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @angular-devkit/build-angular > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning @angular-devkit/build-angular > copy-webpack-plugin > webpack-log > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @angular-devkit/build-angular > webpack-dev-server > sockjs > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @angular-devkit/build-angular > webpack-dev-server > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @angular-devkit/build-angular > istanbul-instrumenter-loader > istanbul-lib-instrument > babel-template > babel-runtime > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning @angular-devkit/build-angular > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @angular/cli > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @angular/cli > ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
warning @angular/cli > universal-analytics > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @angular/cli > universal-analytics > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @angular/cli > @schematics/update > ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
warning @angular/compiler-cli > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @biesbjerg/ngx-translate-extract > chalk@2.0.1: Please upgrade to Chalk 2.1.0 - template literals in this version (2.0.1) are quite buggy.
warning @biesbjerg/ngx-translate-extract > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning @biesbjerg/ngx-translate-extract > flat@2.0.1: Fixed a prototype pollution security issue in 2.0.1, please upgrade to ^2.0.2 or ^5.0.1.
warning cypress > debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning cypress > request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
warning cypress > request > har-validator@5.1.5: this library is no longer supported
warning cypress > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning cypress > extract-zip > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning cypress-image-snapshot@3.1.2: broken deps
warning jest > jest-cli > @jest/core > jest-haste-map > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning jest > jest-cli > @jest/core > jest-haste-map > sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning stylelint > postcss-markdown > remark > unified > @types/vfile > @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
warning wait-on > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning wait-on > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning wait-on > @hapi/joi@15.1.1: Switch to 'npm install joi'
warning wait-on > @hapi/joi > @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
warning wait-on > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
warning wait-on > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
warning wait-on > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning wait-on > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@stoplight/prism-cli > @stoplight/prism-http-server > io-ts-types@0.5.16" has unmet peer dependency "monocle-ts@^2.0.0".
warning "@stoplight/prism-cli > @stoplight/prism-http-server > io-ts-types@0.5.16" has unmet peer dependency "newtype-ts@^0.3.2".
warning " > @uiowa/digit-only@2.2.3" has incorrect peer dependency "@angular/common@>=10.0.0".
warning " > @uiowa/digit-only@2.2.3" has incorrect peer dependency "@angular/core@>=10.0.0".
warning "@angular-builders/jest > jest-preset-angular@7.1.1" has unmet peer dependency "core-js@>=2.0.0 < 4.0.0".
warning " > cypress-image-snapshot@3.1.2" has incorrect peer dependency "cypress@^4.5.0".
[4/4] Building fresh packages...
error /src/app/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /src/app/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.5
node-pre-gyp info using node@14.17.3 | linux | arm64
node-pre-gyp info check checked for "/src/app/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-glibc-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-glibc-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@14.17.3 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v83-linux-glibc-arm64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.17.3 | linux | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.17.3 | linux | arm64
gyp http GET https://nodejs.org/download/release/v14.17.3/node-v14.17.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.17.3/node-v14.17.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.17.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.17.3/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/src/app/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/src/app/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/src/app/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/14.17.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/14.17.3',
gyp info spawn args   '-Dnode_gyp_dir=/src/app/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/14.17.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/src/app/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/src/app/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.9.201-tegra
gyp ERR! command "/usr/local/bin/node" "/src/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/src/app/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/src/app/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /src/app/node_modules/canvas
gyp ERR! node -v v14.17.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /src/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/src/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/src/app/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/src/app/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 4.9.201-tegra
node-pre-gyp ERR! command "/usr/local/bin/node" "/src/app/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /src/app/node_modules/canvas
node-pre-gyp ERR! node -v v14.17.3
node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /src/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/src/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/src/app/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn && yarn build:prod' returned a non-zero code: 1
ERROR: Service 'labeltool-lite-frontend' failed to build : Build failed

**Comment by hadikoub** [comment]
Is this error still valid for the current version?

Please reopen if the error is still persistent
