### ISSUE TITLE
Using yolov4 for labelling automation

### ISSUE THREAD

**Issue by C-monC** [BMW-InnovationLab/BMW-Labeltool-Lite#15]
Hi,

How do you change the pretrained model to a Yolov4 one? Is it all in the config.json under /model?

And there is a small typo in the README. [Line 206 ](https://github.com/BMW-InnovationLab/BMW-Labeltool-Lite/blame/master/README.md#L206) needs all caps .PNG along with some other PNG's

**Comment by HessamSH** [comment]
Any news about this? Looking for the same feature.
