### ISSUE TITLE
Remote access to interface

### ISSUE THREAD

**Issue by torkem** [BMW-InnovationLab/BMW-Labeltool-Lite#18]
Hi,
This is a great tool, I would like to deploy it on a central machine so my colleagues can help in labeling images.
Is there a procedure to enable remote access to the app ?
Right now, the frontend is calling the backend API at http://localhost:8000/api/topics which, of course, doesn't work when connecting from another machine
Thanks !

**Comment by barney2074** [comment]
yes, this would be useful

**Comment by EliteEng** [comment]
If you make a change to the config.json and add your ip address where it says localhost
`nano frontend/code/src/assets/config/config.json`

then run
`docker-compose build`
`docker-compose up`

**Comment by barney2074** [comment]
Thanks Rob

I thought there must be something like that- just couldn't find it

Andrew
